name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        rust: [stable]
        features: ["", proposed]
        os: ["ubuntu-latest", "windows-latest"]

    env:
      CARGO_INCREMENTAL: 0 # Incremental compilation is slower and bloats the cache
      RUST_BACKTRACE: 1

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Build
      run: cargo build

    - name: Fmt
      run: cargo fmt --all -- --check

    - name: clippy
      run: cargo clippy --all-targets -- -D warnings

    - name: Run tests
      run: |
        cargo test --features "${{ matrix.features }}" -- --nocapture
